"""initial schema

Revision ID: c3cbb04ab556
Revises:
Create Date: 2026-06-28 20:25:03.952077

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c3cbb04ab556"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
